File Sharing System/CollegeProject/Controllers/DataController.cs
using CollegeProject.Data;
using CollegeProject.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.IO;
using System.Linq;
using System.Net.WebSockets;
using System.Security.Claims;

namespace CollegeProject.Controllers
{
    [Authorize]
    public class DataController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
		private readonly IWebHostEnvironment _hostingEnvironment;

		public DataController(ApplicationDbContext context, UserManager<ApplicationUser> userManager,
			IWebHostEnvironment hostingEnvironment)
        {
            _context = context;
            _userManager = userManager;
			_hostingEnvironment = hostingEnvironment;
		}
		public IActionResult Index()
        {
			var currentLoginInuserId = new Guid(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
			var fileList = _context.Data.Where(a => a.CreatedBy == currentLoginInuserId).ToList();
            return View(fileList);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(DataModel data, IFormFile ImagePath)
        {
			string fileName = string.Empty;
			if (ImagePath != null && ImagePath.Length > 0)
			{
				var uploadPath = Path.Combine(_hostingEnvironment.WebRootPath, "uploads");
				if (!Directory.Exists(uploadPath))
				{
					Directory.CreateDirectory(uploadPath);
				}
				fileName = $"{Guid.NewGuid().ToString().Substring(0, 5)}_{ImagePath.FileName}";
				string filePath = Path.Combine(uploadPath, fileName);
				ImagePath.CopyTo(new FileStream(filePath, FileMode.Create));

			}
			DataModel dt = new DataModel
            {
                Title = data.Title,
                FileName = fileName,
                CreatedBy = new Guid(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value),
                CreationDate = DateTime.Now
		    };
			_context.Data.Add(dt);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id)
        {
            var dataVM = _context.Data.Where(a=>a.Id == id).FirstOrDefault(); 
            return View(dataVM);
        }
        [HttpPost]
        public IActionResult Edit(DataModel datavm)
        {
			var dvm = _context.Data.Where(a => a.Id == datavm.Id).FirstOrDefault();
            dvm.Title = datavm.Title;
			_context.Data.Update(dvm);
			_context.SaveChanges();
			return RedirectToAction("Index");
		}
        public IActionResult Delete(int id)
        {
			var dataVM = _context.Data.Where(a => a.Id == id).FirstOrDefault();
            _context.Data.Remove(dataVM);
            _context.SaveChanges();
            return RedirectToAction("Index");
		}

        // SHare a file to another user
        public IActionResult Share(int id)
        {
			var currentLoginInuserId = new Guid(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
			ViewBag.FileId = id;
            ViewBag.AllUser = _userManager.Users.Where(a => !a.Id.Equals(currentLoginInuserId)).ToList();
            return View();
        }

        public IActionResult Send(Guid id,int fileId)
        {
            var reciver = _userManager.Users.Where(a=>a.Id == id).First();
            var sender = new Guid(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
			var fileInfo = _context.Data.Where(a=>a.Id==fileId).FirstOrDefault();

            if (fileInfo != null && reciver != null)
            {
                ShareModel share = new ShareModel
                {
                    Fileid = fileId,
                    IsCompleted = false,
                    ReciverId = id,
                    CreatedBy = sender,
					CreationDate = DateTime.Now,
				};
                _context.Share.Add(share);
                _context.SaveChanges();
            }
			TempData["SuccessMessage"] = "File Sent. Wait for admin approval";
			return RedirectToAction("Share", new { id = fileId,});
        }

        public IActionResult ShareInfo()
        {
			var currentLoginInuserId = new Guid(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
			var shareData = _context.Share.Include(a=>a.Data).Include(a => a.Reciever).Where(a => a.CreatedBy == currentLoginInuserId).ToList();
            return View(shareData);
        }

		[Authorize(Roles = RoleTypes.Administrator)]
		public IActionResult ShareApproval()
        {
			var shareData = _context.Share.Include(a => a.Data).Include(a => a.Reciever).Where(a=>a.IsCompleted == false).ToList();
			return View(shareData);
		}


        [Authorize(Roles = RoleTypes.Administrator)]
        public IActionResult Approved(int id)
        {
            var share = _context.Share.Where(a => a.Id == id).SingleOrDefault();
            if (share != null)
            {
                share.IsCompleted = true;
                _context.Share.Update(share);
                _context.SaveChanges();
            }
			TempData["SuccessMessage"] = "File Approved";
			return RedirectToAction("ShareApproval");
        }

        public IActionResult Inbox()
        {
            var currentLoginInuserId = new Guid(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            var inboxList = _context.Share.Include(a => a.Data).Include(a => a.CreatedUser).Where(a => a.ReciverId == currentLoginInuserId && a.IsCompleted).ToList();
            return View(inboxList);
        }
    }
}

File Sharing System/CollegeProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CollegeProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css">

    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CollegeProject</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Data" asp-action="Inbox">Inbox</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Data" asp-action="Index">Data</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Data" asp-action="ShareInfo">SharedFile Status</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CollegeProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>